# Generated by Django 4.1.3 on 2022-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=122)),
                ('LName', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=122)),
                ('PhoneNo', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=122)),
                ('Age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=122)),
                ('Last_Name', models.CharField(max_length=122)),
                ('Age', models.PositiveIntegerField()),
                ('PhoneNo', models.CharField(max_length=107)),
                ('Email', models.EmailField(max_length=122)),
                ('Specialization', models.CharField(max_length=255)),
                ('Achievements', models.FileField(default='', upload_to='ArtistForm/images')),
                ('Art', models.FileField(default='', upload_to='ArtistForm/images')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('First_Name', models.CharField(max_length=122)),
                ('Last_name', models.CharField(max_length=122)),
                ('Employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=122)),
                ('PhoneNo', models.CharField(max_length=107)),
                ('Email', models.EmailField(max_length=122)),
                ('Age', models.PositiveIntegerField()),
                ('DOB', models.DateField()),
                ('Blood_Group', models.CharField(max_length=107)),
                ('Address', models.TextField()),
                ('DOJ', models.DateField()),
                ('Department', models.IntegerField(choices=[(1, 'Select'), (2, 'Receptionist'), (2, 'Security'), (3, 'Management')], default=1)),
                ('username', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=122)),
                ('Last_Name', models.CharField(max_length=122)),
                ('PhoneNo', models.CharField(max_length=107)),
                ('Email', models.EmailField(max_length=122)),
                ('Address', models.TextField()),
                ('Address2', models.TextField(default='Nothing')),
                ('Country', models.CharField(max_length=255)),
                ('States', models.CharField(max_length=255)),
                ('zipcode', models.PositiveBigIntegerField()),
                ('Payment', models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Debit Card')])),
            ],
        ),
        migrations.CreateModel(
            name='VisiterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=122)),
                ('LName', models.CharField(max_length=122)),
                ('Booking_Date', models.DateField()),
                ('Email', models.EmailField(max_length=122)),
                ('Timing', models.TimeField()),
                ('NoC', models.PositiveIntegerField()),
                ('NoA', models.PositiveIntegerField()),
                ('PhoneNo', models.CharField(max_length=107)),
                ('Booking_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=122)),
                ('LName', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=122)),
                ('PhoneNo', models.CharField(max_length=107)),
                ('username', models.CharField(max_length=122)),
                ('Age', models.PositiveIntegerField()),
            ],
        ),
    ]
