# Generated by Django 4.1.3 on 2022-11-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0003_transaction_payment_noa_transaction_payment_noc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Payment',
        ),
    ]
