# Generated by Django 4.1.3 on 2022-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0005_transaction_datetime_of_payment_transaction_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Payment_NoA',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Payment_NoC',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
