# Generated by Django 4.1.3 on 2022-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0006_alter_transaction_payment_noa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.IntegerField(choices=[(1, 'Select'), (2, 'Receptionist'), (2, 'Security'), (3, 'Management'), (4, 'Tech')], default=1),
        ),
    ]
