# Generated by Django 4.1.3 on 2022-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0007_alter_employees_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=122)),
                ('Last_Name', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=122)),
                ('PhoneNo', models.PositiveIntegerField()),
                ('Username', models.CharField(max_length=122)),
                ('STAR', models.IntegerField()),
                ('Feedback', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
