# Generated by Django 4.1.3 on 2022-11-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0008_review_employees_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewSection',
        ),
    ]
