# Generated by Django 4.1.3 on 2022-11-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0009_rename_review_reviewsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsection',
            name='PhoneNo',
        ),
    ]
