# Generated by Django 4.2.1 on 2023-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGMAapp', '0010_remove_reviewsection_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.IntegerField(choices=[(1, 'Select'), (2, 'Receptionist'), (3, 'Security'), (4, 'Management'), (5, 'Tech')], default=1),
        ),
    ]
